#!/bin/bash

usage()
{
  echo "Usage: members-mail-contributions.sh [-t template-file] mail-file"
  echo "-t     reads mail template addresses"
  echo ""
  echo "reads a mail file and generates output file for mailing letters"
  echo "- the mail file is generated by the bank-transaction-read.sh using -m"
  echo "- the mail template addresses is a letter containing macro's"
  echo "  that will be substituted:"
  echo "  ACCOUNT"
  echo "  CONTRIB"
  echo "  EMAIL"
  echo "  NAME"
  echo "  SIGNATURE"
  echo "  YEAR"
  echo ""
  echo "It creates a file mail-them.sh that you can inspect and just execute"
  echo "for the actual mailing"
}

while getopts ":t:h" opt; do
  case $opt in
    h)
      usage
      exit 1
    ;;

    t)
      export FILE_TEMPLATE="${OPTARG}"

      if [[ ! -f $FILE_TEMPLATE ]]
      then
        echo "info file $FILE_TEMPLATE does not exist"
        exit 1
      fi
    ;;

    :)
      echo "option -${OPTARG} requires an argument"
      exit 1
    ;;

    ?)
      echo -e "option -$OPTARG not supported"
      exit 1
    ;;
  esac
done

shift "$(($OPTIND -1))"

if [[ $# -ne 1 ]]
then
  usage
  exit 1
fi

input=$1

if [[ ! -f $1 ]]
then
  echo "input file $1 does not exist"
  exit 1
fi

if [ -z "$FILE_TEMPLATE" ]; then
  echo 'Missing -t' >&2
  exit 1
fi

output=$1-mail
scriptdir="$(dirname -- "$BASH_SOURCE";)"

awk -f ${scriptdir}/members-mail.awk $input > $output
